### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by einsamkeid** [einsamkeid/SEBC#2]
Installation Lab

**Comment by mfernest** [comment]
What lab section are you currently working on?

**Comment by einsamkeid** [comment]
[root@ip-10-0-0-122 ~]# service cloudera-scm-server start
Starting cloudera-scm-server:                              [  OK  ]
[root@ip-10-0-0-122 ~]# service cloudera-scm-server status
cloudera-scm-server dead but pid file exists
================================
i couldn't find the reason

**Comment by mfernest** [comment]
Did you check the log file? `/var/log/cloudera-scm-server/cloudera-scm-server.log`

**Comment by einsamkeid** [comment]
i finished

**Comment by mfernest** [comment]
`1_preinstall.md` - steps 2, 3, and 4 are either incorrect or incomplete. In step 2, the mount table is expected, not the filesystem space table. In step 3, the command that shows reserve space is expected (there is one for ext3 and ext4). Step 4 is incomplete.

Please complete these elements and remove the `incomplete` flag from this issue when done.

**Comment by einsamkeid** [comment]
In 1_preinstall.md
step2, step3, step4 is appended
(i installed CentOS 6.5 )

**Comment by mfernest** [comment]
Output of `SHOW SLAVE STATUS \G` shows the replica is not working.
