### ISSUE TITLE
YARN/RM Lab

### ISSUE THREAD

**Issue by einsamkeid** [einsamkeid/SEBC#4]
YARN/RM Lab

**Comment by einsamkeid** [comment]
becouse of  lack of disk for CM ( in aws)
i am expanding cm volume ( 30G -> 100G )

**Comment by einsamkeid** [comment]
AWS PUblic ip changed ( to :  54.254.211.76 )

**Comment by einsamkeid** [comment]
after i executed sh script
but i could'not see anything in yarn application chart ( user : root )

I all submit ( finished)

**Comment by mfernest** [comment]
Did you look for the utilization reports for YARN? The screen capture is too fuzzy for me to read.
👍
